"""Run every test case and print a results table.

Usage (from the project folder):   python tests/run_tests.py
Also writes docs/test_results.md with the real results of this run.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from tests.cases import CASES, Contains  # noqa: E402


def short(value, limit=38):
    text = repr(value) if not isinstance(value, type) else value.__name__
    text = text.replace("\n", " ").replace("|", "/")
    return text if len(text) <= limit else text[:limit - 3] + "..."


def evaluate(function, args, expected):
    """Return (actual_text, passed)."""
    try:
        result = function(*args)
    except Exception as error:  # noqa: BLE001 - tests must catch everything
        if isinstance(expected, type) and isinstance(error, expected):
            return expected.__name__, True
        return f"{type(error).__name__}: {error}", False
    if isinstance(expected, Contains):
        return ("contains text" if expected.text in result else "text missing"), expected.text in result
    if isinstance(expected, type):
        return f"no error, got {short(result)}", False
    return short(result), result == expected


def main():
    rows, passed = [], 0
    for case_id, description, function, args, expected in CASES:
        actual, ok = evaluate(function, args, expected)
        passed += ok
        shown_input = "(none)" if args == () else short(args)
        if isinstance(expected, Contains):
            shown_input = "keys: " + short(args[0])
        exp_text = short(expected) if not isinstance(expected, Contains) else f"contains '{expected.text}'"
        if isinstance(expected, type):
            exp_text = f"raises {expected.__name__}"
        rows.append((case_id, description, shown_input, exp_text, actual, "PASS" if ok else "FAIL"))

    header = "| Test ID | Description | Input | Expected Result | Actual Result | Status |"
    lines = [header, "|---|---|---|---|---|---|"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    table = "\n".join(lines)
    print(table)
    print(f"\nTotal: {len(rows)}   Passed: {passed}   Failed: {len(rows) - passed}")

    with open(os.path.join(ROOT, "docs", "test_results.md"), "w", encoding="utf-8") as out:
        out.write("# Test Results\n\nGenerated by `python tests/run_tests.py`.\n\n")
        out.write(table + f"\n\n**Total: {len(rows)} | Passed: {passed} | Failed: {len(rows) - passed}**\n")
    sys.exit(0 if passed == len(rows) else 1)


if __name__ == "__main__":
    main()
